// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import DropdownController from "./dropdown_controller"
import ConfirmDeleteController from "./confirm_delete_controller"
import PostFormController from "./post_form_controller"

application.register("hello", HelloController)
application.register("dropdown", DropdownController)
application.register("confirm-delete", ConfirmDeleteController)
application.register("post-form", PostFormController)
